// (C) 2012 Masatoshi Teruya <http://twitter.com/mah0x211>
'use strict';var j=void 0,l=!0,r=null,s=!1,Rez={__proto__:r},aa=Rez;function y(a,b){for(var c=a+"\n    "+b.src+"\n    ",d=b.d,i=0;i<d;i++)c+=" ";return c+=ba}function z(a,b){var c=A[""+b.type];a.l=c?new SyntaxError(y(c+" token disallowed here",a)):new SyntaxError(y("unknown token:"+b.type+" disallowed here",a))}function B(a,b,c){a.state.o&b.type||a.state.type===C?(a.state.b.push(b),c&&(a.state.o=c)):z(a,b)}
function D(a,b,c,d){a.state=c?{__proto__:r,r:a.state,o:d||a.state.o,type:b,c:c,b:c.a}:{__proto__:r,r:a.state,o:d||a.state.o,type:b,c:a.state.c,b:a.state.b}}function E(a){a.state=a.state.r}function F(a,b,c){for(var d=c,i=ca[c],h=0,h=j,h=0;h<i;h++){d+=a.e.charAt(h);if(!ca[d])break;c=d}h&&(a.e=a.e.substring(h));(h=da[c])?(h(a,b,c),a.d+=c.length):a.l=new SyntaxError(y("undefined symbol processor:"+c,a))}
function ea(a,b,c){b||(b=a.state.b[a.state.b.length-1]);b&&b.type!==G&&fa&b.type?H(a,b,c):ga(a,0,c)}function ha(a,b,c){b?z(a,{type:ia,t:c}):(b=a.state.b[a.state.b.length-1],!b||b.type!==I?z(a,{type:ia,t:c}):D(a,G,b,G));a.d++}function ja(a,b,c){B(a,{__proto__:r,type:ka,a:c},J);a.d++}function K(a,b,c){B(a,{__proto__:r,type:la,a:c},J)}function L(a,b,c){var b=J,d=a.state.b[a.state.b.length-1];"="!==c&&"+"!==c.charAt(0)&&(b&=~M);d.type=ma;B(a,{__proto__:r,type:na,a:c},b)}
function ga(a,b,c){B(a,{__proto__:r,type:pa,a:c},N|M|qa|I)}function H(a,b,c){b||(b=a.state.b[a.state.b.length-1]);b&&b.type===M&&"+"!==c?a.l=new SyntaxError(y("literal token allowed only arithmetic:+ token",a)):(b=J,"+"!==c&&(b&=~M),B(a,{type:ra,a:c},b))}function sa(a,b,c){b?z(a,{type:O,a:c}):(c={__proto__:r,type:O,a:[]},b=a.state.b[a.state.b.length-1],b.a.push(c),D(a,O,c,J));a.d++}
function ta(a,b,c){b||(b=a.state.b[a.state.b.length-1]);a.state.type===O&&b&&fa&b.type?(a.state.c.type=P,E(a)):z(a,{type:ua,a:c});a.d++}function va(a){var b={__proto__:r,type:Q,a:[]};B(a,b);D(a,Q,b,J)}
function wa(a,b,c){if(b)a.l=new SyntaxError(y("left token must be nothing",a));else{for(var b=a.e,d=0,i=c.length,h=0,e;-1!==(d=b.indexOf(c,d));){if(!(d&&92===b.charCodeAt(d-1))){var f=0;e=d;do e--,e=b.lastIndexOf(c,e);while(f++<h);if(-1===e||0===e)break}h++;d+=i}-1===(c=d)?a.l=new SyntaxError(y("ending mark of literal token not found",a)):(B(a,{__proto__:r,type:M,a:a.e.substring(0,c)},xa),a.e=a.e.substring(c+1),a.d+=c+2)}}
function ya(a,b,c){if(a.state.type===G){var d={__proto__:r,type:O,a:[]};E(a);sa(a,j,"[");B(a,b);ta(a,b,"]");"["===c?sa(a,j,"["):"."===c&&ha(a,j,".")}else a.state.type===za?(d=a.state.c,d.type=b.type=za,d.a[0].a+="."+b.a[0].a,E(a)):(B(a,b,xa),"."===c?D(a,za,b,Aa):"["===c&&z(a,{type:O,t:c}))}
function Ca(a,b,c){if(a.state.type===G)B(a,b.a[0]),"."!==c&&(b=a.state.c,E(a),"["===c&&(c={__proto__:r,type:O,a:[]},b.a.push(c),D(a,O,c,J)));else{var d=ka|la|ra|O,i=a.state.b[a.state.b.length-1],h=a.state.b.length;switch(a.state.type){case Aa:case O:case N:if(!h||!i)d|=na}B(a,b,d);"."===c?D(a,G,b,G):"["===c&&(c={__proto__:r,type:O,a:[]},b.a.push(c),D(a,O,c,J))}}
function Da(a){var b={__proto__:r,type:Ea,a:j};isFinite(+a)?(b.type=Fa,b.a=[{__proto__:r,type:Fa,a:a}]):Ga.test(a)?(b.type=I,b.a=[{__proto__:r,type:G,a:a}]):b.a=a;return b}
var ba="^",Ha=RegExp(/[\x21\x22\x25-\x2f\x3c-\x3e\x5b\x5d\x5e\x7c\x7e]|\s+/),Ia=RegExp(/^\s+/),Ga=RegExp(/^#?(?:@|\${1,2})?[_a-zA-Z]\w{0,}$/),ca={__proto__:r,"+":2,"+=":1,"-":2,"-=":1,"*":2,"*=":1,"/":2,"/=":1,"%":2,"%=":1,"~":1,"&":2,"&=":1,"&&":1,"|":2,"|=":1,"||":1,"^":2,"^=":1,"=":3,"==":2,"===":1,"!":3,"!=":2,"!==":1,"<":3,"<=":1,"<<":1,"<<=":1,">":3,">=":1,">>":1,">>=":1},La={__proto__:r," ":function(a){var b=Ia.exec(a.e);b?(a.d+=b[0].length+1,a.e=a.e.substring(b[0].length)):a.d++},",":function(a,
b,c){a.state.type===Q?(E(a),va(a)):z(a,{type:Ja,a:c});a.d++},'"':wa,"'":wa,".":ha,"(":function(a){var b={__proto__:r,type:N,a:[]};B(a,b,xa);D(a,N,b,J);a.d++},")":function(a,b,c){if(a.state.type===N)b||(b=a.state.b[a.state.b.length-1]),b&&fa&b.type?(a.state.c.type=R,E(a)):z(a,{type:Ka,a:c});else if(a.state.type===Q){var d=l;b||(b=a.state.b[a.state.b.length-1]);b?fa&b.type?E(a):(d=s,z(a,{type:Ka,a:c})):(E(a),a.state.b.pop());d&&(a.state.type===C?E(a):z(a,{type:Ka,a:c}))}else z(a,{type:Ka,a:c});a.d++},
"[":sa,"]":ta,"+":F,"-":F,"*":F,"/":F,"%":F,"~":F,"&":F,"|":F,"^":F,"<":F,">":F,"=":F,"!":F},da={__proto__:r,"&&":ja,"||":ja,"<":K,"<=":K,">":K,">=":K,"==":K,"===":K,"!=":K,"!==":K,"=":L,"+=":L,"-=":L,"*=":L,"/=":L,"%=":L,"<<=":L,">>=":L,"&=":L,"|=":L,"^=":L,"~":ga,"!":ga,"+":ea,"-":ea,"*":H,"/":H,"%":H,"<<":H,">>":H,"&":H,"|":H,"^":H},Aa=0,Ea=1,ia=4,Ja=8,ka=16,la=32,na=64,pa=128,ra=256,N=512,Ka=1024,R=N|Ka,O=2048,ua=4096,P=O|ua,C=8192,Q=16384,M=32768,Fa=65536,za=131072,qa=Fa|za,I=262144,ma=524288,
G=1048576,J=pa|N|C|M|qa|I,xa=ka|la|ra,fa=R|P|C|M|qa|I,A={__proto__:r,2:"space"};A[""+ia]="reference operator";A[""+Ja]="comma separator";A[""+ka]="logical";A[""+la]="relational";A[""+na]="assignment";A[""+pa]="unary";A[""+ra]="arithmetic";A[""+N]="open parenthesis";A[""+Ka]="closed parenthesis";A[""+R]="parentheses";A[""+O]="open bracket";A[""+ua]="closed bracket";A[""+P]="brackets";A[""+C]="function";A[""+Q]="argument";A[""+M]="literal";A[""+Fa]="integral number";A[""+za]="real number";
A[""+qa]="number";A[""+I]="variable";A[""+ma]="variable assignment";A[""+G]="member field";
var Ma={__proto__:r,H:Aa,ia:Ea,N:ka,Q:la,z:na,T:pa,L:ra,O:R,Z:P,u:C,K:Q,R:M,M:Fa,P:za,v:I,C:ma,B:G,analyze:function(a){var a={src:a,e:a,b:[],o:J,d:0,l:s,state:{__proto__:r,r:j,o:J,type:0,c:j,b:j}},b="",c="",d,i;for(a.state.b=a.b;!a.l&&(i=Ha.exec(a.e));)if(d=i.index,c=i[0].trim(),b=a.e.substring(0,d).trim(),a.d+=d,a.e=a.e.substring(d+1),c||(c=" "),d=La[c]){if(b)if(b=Da(b),b.type===Ea){a.l=new SyntaxError(y("unknown left token",a));break}else if(b.type===Fa){if(ya(a,b,c),"."===c||"["===c)continue}else if("("===
c){b.type=C;c=a;d=b;B(c,d,xa);D(c,C,d,Q);va(c);continue}else if(Ca(a,b,c),"."===c||"["===c)continue;d(a,b,c)}else a.l=new SyntaxError(y("undefined symbol processor["+c+"]",a));if(!a.l&&(b=a.e.trim()))b=Da(b),b.type&Ea?a.l=new SyntaxError(y("left token must be variable or number token",a)):b.type===Fa?ya(a,b):Ca(a,b),a.d+=a.e.length;a.l||(a.state.type?a.l=new SyntaxError(y("no end of state token for "+A[""+a.state.type],a)):(b||(b=a.state.b[a.state.b.length-1]))&&!(fa&b.type)&&z(a,b));return{error:a.l,
g:a.b}},restore:function(a){var b="",a={list:a,w:a.length,d:0,s:0,r:j},c=a.list,d=a.w,i=0,h=j;a:for(;a.d<d;){h=c[a.d++];if((2|ka|la|na|pa|ra)&h.type)b+=h.a;else if(M===h.type)b+="'"+h.a+"'";else if(qa&h.type)b+=h.a[0].a;else if(G===h.type){if(G===i||ua===i||P===a.s)b+=".";b+=h.a;a.s===C&&(b+="(")}else(I|ma|C|Q|P|R)&h.type&&(h.type===P?b+="[":h.type===R&&(b+="("),a={list:h.a,w:h.a.length,d:0,s:h.type,r:a},c=a.list,d=a.w);for(i=h.type;a.d===d;)if(a.s===P?(b+="]",i=ua):a.s===R?(b+=")",i=R):a.s===Q?b+=
",":a.s===C&&(b=b.replace(/,\s*$/,"")+")"),a.r)a=a.r,c=a.list,d=a.w;else break a}return b}};Object.freeze(Ma);aa.lexer=Ma;var Na=Rez,S=Rez.lexer;function Oa(a){var b={I:"''",prefix:Pa,a:j,t:a.charAt(0)},c=0;b.t===Qa&&(b.I="0",b.t=a.charAt(1),c++);b.t===Ra?(b.prefix=Sa,c++):b.t===Ta&&(a.charAt(c+1)===Ta?(b.prefix=Ua,c+=2):(b.prefix=Va,c++));b.a=a.substring(c);return b}function T(a){return'CTX.out += "'+a.replace(Wa,"\\n").replace(Xa,'\\"')+'";\n'}
function Ya(a,b,c){var d={__proto__:r,code:j,error:j};d.code=c?Za+a[0].a+"( "+$a+", ":ab+a[0].a+"( ";1<a.length&&(a=U(a.slice(1),b),a.error?d.error=a.error:d.code+=a.code.replace(bb,""));d.code+=" )";return d}
function U(a,b){var c={__proto__:r,code:"",error:j},d=a.length,i=0,h,e;a:for(;i<d;)switch(h=a[i++],h.type){case S.N:case S.Q:case S.T:case S.L:c.code+=h.a;break;case S.R:case S.B:c.code+="'"+h.a+"'";break;case S.M:case S.P:c.code+=h.a[0].a;break;case S.v:h=h.a;e=b;for(var f=h.length,g=Oa(h[0].a),q=g.prefix+"."+g.a,oa=1,n={__proto__:r,code:"( "+q,error:j},k=j,m=k=j,oa=1;oa<f;){k=h[oa++];if(k.type===S.B)q+="."+k.a;else if(m=U(k.a,e),m.error){n.error=m.error;break}else k=V+e.h++,e.code+=k+X+m.code+Y,
q+="["+k+"]";n.code+=" && "+q}n.error||(n.code=n.code+" || "+g.I+" )");e=n;if(e.error){c.error=e.error;break a}c.code+=e.code;break;case S.z:case S.C:c.error=new TypeError("assignment operation does not allowed here");break a;case S.u:e=Ya(h.a,b,s);if(e.error){c.error=e.error;break a}c.code+="( "+ab+h.a[0].a+" && "+e.code+" || '' )";break;case S.K:e=U(h.a,b);if(e.error){c.error=e.error;break a}c.code+=", "+e.code;break;case S.O:e=U(h.a,b);if(e.error){c.error=e.error;break a}c.code+="( "+e.code+" )";
break;default:c.error=new TypeError("unknown token: "+h.type);break a}return c}function cb(a,b){var c={type:b,code:"",q:"",p:j,error:j};b===db||b===Z?c.p=eb:b===fb?(c.p=eb,a.loop++):c.p="";a.stack.push(c);a.state=c;a.h++;return c}
function gb(a,b,c){var d={__proto__:r,e:$a,src:j},i={__proto__:r,code:"",h:0},h={loop:0,h:-1,stack:[],state:j},e=cb(h,hb),f,g;c?(d.name=j,e.code=ib):(d.macro={__proto__:r},e.code=jb);for(var q=0,oa=b.length;q<oa;q++)if(f=b[q],f.error)e.code+=T(f.c);else if(f.F)if(h.h){var e=h,n=e.state;e.h--;e.state=e.stack[e.h];e.stack.pop();switch(n.type){case fb:e.loop--;e.state.code+=n.q+n.code;break;case db:case Z:case kb:e.state.code+=n.q+n.code;break;default:e.state.code+=T(f.c)}e.state.code=n.error?e.state.code+
T(f.c):e.state.code+n.p;e=e.state}else h.state.code+=T(f.c);else if(f.type!==lb)switch(i.code="",e.type||(i.h=0),f.type){case mb:g=U(f.b,i);g.error?(f.error=e.error=g.error,a.m.push(f),e.code+=T(f.c)):e.code+=i.code+"CTX.out += "+g.code+Y;break;case nb:n=f.b;g=i;var k={__proto__:r,code:"",error:j};if(3>n.length||n[0].type!==S.C||n[1].type!==S.z)k.error=new SyntaxError("invalid opSet syntax");else{var m;m=n[0].a;var p=g,o={__proto__:r,code:"",error:j},x=m.length,t=Oa(m[0].a);if(1===x)o.code="this.InitProperty( "+
t.prefix+", '"+t.a+"' )."+t.a;else{var u=1,w=j,v=j,v=j;for(o.code="this.InitProperty( "+t.prefix+", '"+t.a+"'";u<x;u++)if(w=m[u],w.type===S.B)o.code+=", '"+w.a+"'";else if(v=U(w.a,p),v.error){o.error=v.error;break}else w=v.code,o.code+=", "+w;o.error||("string"===typeof w?(x=o.code.length-w.length,v=V+p.h++,p.code+=v+X+w+Y,o.code=o.code.substring(0,x)+v+" )["+v+"]"):o.code+=" )."+w.a)}m=o;m.error?k.error=m.error:(k.code+=m.code+n[1].a,m=U(n.slice(2),g),m.error?k.error=m.error:k.code+=m.code)}g=k;
g.error?(f.error=e.error=g.error,a.m.push(f),e.code+=T(f.c)):e.code+=i.code+g.code+Y;break;case db:e=cb(h,db);g=U(f.b,i);g.error?(f.error=e.error=g.error,a.m.push(f),e.code=T(f.c)):e.code=i.code+"if( ( ALT = "+g.code+" ) ){\nCTX.out += ALT;\n} else {\n";break;case Z:e=cb(h,Z);g=U(f.b,i);g.error?(f.error=e.error=g.error,a.m.push(f),e.code+=T(f.c)):(e.q=i.code,e.code="if( "+g.code+" ){\n");break;case ob:!e.error&&e.type===Z?(g=U(f.b,i),g.error?(f.error=e.error=g.error,a.m.push(f),e.code+=T(f.c)):(e.q+=
i.code,e.code+="} else if( "+g.code+" ){\n")):e.code+=T(f.c);break;case pb:e.code=!e.error&&e.type===Z?e.code+"} else {\n":e.code+T(f.c);break;case fb:e=cb(h,fb);g=f.b;k=i;n={__proto__:r,code:"",error:j};m=g.length;if(3>m)n.error=new SyntaxError("error");else{p=qb[0];x=o=0;for(t=j;o<m;o++)if(t=g[o],t.type===p.type)p.a=t.a,p=qb[++x];else{n.error=new SyntaxError("error");break}if(3===x&&1===rb.a.length)if(sb=tb.a[0].a,sb===ub)if(g=n,p=tb.a,o=p.length,4!==o)g.error=new SyntaxError("opLoop invalid arguments");
else{m=Oa(rb.a[0].a);x=m.prefix+"."+m.a;t=[" = "," < "," += "];m=[];for(var u=1,w=0,Ba=v=j;u<o;u++){v=V+k.h++;Ba=U(p[u].a,k);if(Ba.error){g.error=Ba.error;break}k.code+=v+X+"+( "+Ba.code+" )"+Y;g.code+=x+t[w]+v+"; ";m[w++]=v}g.error||(p=V+k.h++,k=V+k.h++,g.code="if( isFinite( "+m[0]+" ) && isFinite( "+m[1]+" ) && isFinite( "+m[2]+" ) ){\n"+p+X+m[1]+" - "+m[0]+Y+p+X+"( "+p+" ^ ( "+p+" >> 31 ) ) - ( "+p+" >> 31 )"+Y+k+X+m[1]+" - ( "+m[0]+" + "+m[2]+" )"+Y+k+X+"( "+k+" ^ ( "+k+" >> 31 ) ) - ( "+k+" >> 31 )"+
Y+"if( "+k+" < "+p+" ){\nfor( "+g.code.replace(vb,"")+" ){\n")}else if(sb===wb)if(g=n,o=k,k=tb.a,t=k.length,x=s,2===t||(x=3===t))if(t=U(k[1].a,o),t.error)g.error=t.error;else{if(u=Oa(rb.a[0].a),m=u.prefix+"."+u.a,p=V+o.h++,u=V+o.h++,w=V+o.h++,v=V+o.h++,o.code+=p+X+t.code+Y,g.code="if( typeof "+p+" === 'object' ){\n"+u+X+"Object.keys( "+p+" )"+Y+w+X+u+".length"+Y+v+X+"0"+Y+"for(; "+v+" < "+w+"; "+v+"++ ){\n"+m+X+u+"["+v+"]"+Y,x){o=0;u=x=j;k=k[2].a;for(t=k.length;o<t;o++)if(x=k[o],x.type===S.v){if(u||
1<x.a.length){g.error=new SyntaxError("opLoopEach invalid arguments");break}u=Oa(x.a[0].a);g.code+=u.prefix+"."+u.a+X+p+"["+m+"]"+Y}else{g.error=new SyntaxError("opLoopEach invalid arguments");break}}}else g.error=new SyntaxError("opLoopEach invalid arguments");else n.error=new SyntaxError("unknown loop command: "+sb);else n.error=new SyntaxError("error")}g=n;g.error?(f.error=e.error=g.error,a.m.push(f),e.code+=T(f.c)):(e.q=i.code,e.code=g.code,e.p=sb===ub?e.p+(eb+eb):e.p+eb);rb.a=j;xb.a=j;sb=tb.a=
j;break;case yb:e.code=!e.error&&h.loop?e.code+"break;\n":e.code+T(f.c);break;case zb:k=f.b;m=i;n={__proto__:r,code:"",error:j};g=k[0];1!==k.length||g.type!==S.u?n.error=new SyntaxError("invalid macro call syntax"):(k=Ya(g.a,m,l),k.error?n.error=k.error:n.code="if( "+Za+g.a[0].a+" ){\n"+k.code+Y+"} else {\nCTX.out += 'undefined macro "+g.a[0].a+"';\n}\n");g=n;g.error?(f.error=e.error=g.error,a.m.push(f),e.code+=T(f.c)):e.code+=i.code+g.code;break;case Ab:c?(f.error=new SyntaxError("invalid nested macro"),
a.m.push(f),e.code+=T(f.c)):(g=gb(a,f.g,l),g.name?d.macro[g.name]={e:g.e,src:g.src}:e.code+=g.code);break;case kb:n=e;e=cb(h,kb);g=d;p=f.b;k={__proto__:r,code:"",error:j};m=p.length;p=p[0];if(1!==m||p.type!==S.u)k.error=new SyntaxError("invalid macro call syntax");else{o=p.a;x=o.length;v=w=u=t=j;g.name=p.a[0].a;for(w=1;w<x;w++){t=o[w].a;m=t.length;for(v=0;v<m;v++)if(p=t[v],p.type===S.v&&1===p.a.length)u=p.a[0].a,g.e+=", "+u,k.code+=Sa+"."+u+" = "+u+Y;else{k.error=new SyntaxError("invalid macro declare argument");
g.name=j;break}}}g=k;g.error?(f.error=e.error=g.error,a.m.push(f),n.code="",e.code=T(f.c)):e.code+=g.code;break;default:e.code+=T(f.c)}d.src=e.q+"\n"+e.code;return d}
var Wa=RegExp(/\n/g),Xa=/"/g,bb=RegExp(/^(?:,\s*)+/),vb=RegExp(/;\s*$/),Qa="#",Ta="$",Ra="@",ub="for",wb="each",Pa="UDATA",Va="LOCAL",Ua="TMP",V="PREP.$",Sa="ARGS",$a="CTX, UDATA, LOCAL",jb='"use strict"\nvar PREP = { __proto__: null }, TMP = { __proto__: null }, ALT;\n',ib='"use strict"\nvar PREP = { __proto__: null }, TMP = { __proto__: null }, ARGS = { __proto__: null }, ALT;\n',Za="this.M$",ab="this.B$",X=" = ",Y=";\n",eb="}\n",rb={__proto__:r,type:S.C,a:j},xb={__proto__:r,type:S.z,a:j},tb={__proto__:r,
type:S.u,a:j},sb=j,qb=[rb,xb,tb],hb=0,Ab=1,lb=2,mb=4,nb=8,db=16,Z=32,ob=64,pb=128,fb=256,yb=512,kb=1024,zb=2048,Bb={__proto__:r,"var":{__proto__:r,type:mb,f:1,k:0,n:0,state:"",j:0,i:0},set:{__proto__:r,type:nb,f:1,k:0,n:0,state:"",j:0,i:0},alt:{__proto__:r,type:db,f:1,k:1,n:0,state:"",j:0,i:0},"if":{__proto__:r,type:Z,f:1,k:1,n:0,state:"",j:0,i:0},elif:{__proto__:r,type:ob,f:1,k:0,n:Z,state:"if",j:0,i:0},"else":{__proto__:r,type:pb,f:0,k:0,n:Z,state:"if",j:0,i:0},loop:{__proto__:r,type:fb,f:1,k:1,
n:0,state:"",j:1,i:0},"break":{__proto__:r,type:yb,f:0,k:0,n:fb,state:"loop",j:0,i:0},macro:{__proto__:r,type:kb,f:1,k:1,n:0,state:"",j:0,i:1},call:{__proto__:r,type:zb,f:1,k:0,n:0,state:"",j:0,i:0},escape:{__proto__:r,type:4096,f:1,k:1,n:0,state:"",j:0,i:0}};Object.freeze(Bb);
var Cb={__proto__:r,toString:function(a){for(var b="",c=0,d=a.length;c<d;c++)if(f=a[c],f.error)b+=f.error+"\n";else if(f.type)if(f.type===Ab)for(var i=f.g,h=0,e=i.length;h<e;h++)var f=i[h],b=f.error?b+(f.error+"\n"):b+f.c;else b+=f.c;else b+=f.c;return b},toCode:gb,ca:-1,H:0,S:1,A:2,v:4,ha:8,X:16,ea:32,aa:64,ba:128,fa:256,Y:512,ga:1024,$:2048,da:4096},Db;for(Db in Bb)"object"===typeof Bb[Db]&&Object.freeze(Bb[Db]),Cb[Db]=Bb[Db];Object.freeze(Cb);Na.generator=Cb;var Eb=Rez,Fb=Rez.lexer,$=Rez.generator;
function Gb(a){var b=a.D,c=b.indexOf(Hb,a.offset),a=j;if(0<=c)if(a={__proto__:r,type:-1,start:c,end:b.indexOf(Ib,c),error:j},0>a.end)a.end=c+1,a.error=new SyntaxError("Missing ending bracket '"+Ib+"' at "+b.substring(c,c+15));else{var b=b.substring(c,a.end+=Jb),c=b.indexOf(Kb,Lb),d;-1!==c?(a.end=a.start+c,a.error=new SyntaxError("Invalid syntax at "+b.substring(0,15))):(c=Mb.exec(b))?c[Nb]?a.type=$.A:!(a.name=c[Ob])||!(d=$[a.name])?a.error=new SyntaxError("Invalid syntax - unknown syntax at "+b):
(a.type=d.type,c[Pb]&&(a.f=c[Pb].replace(Qb,"")),a.F=c[Rb]?l:s)?d.k?a.f&&(a.error=new SyntaxError("Invalid syntax - end of block syntax disallowd any expressions: "+b)):a.error=new SyntaxError("Invalid syntax - "+a.name+" is inline syntax: "+b):a.f?d.f?(d=Fb.analyze(a.f),d.error?a.error=new SyntaxError("Invalid syntax - "+a.name+"\n"+d.error.message):a.b=d.g):a.error=new SyntaxError("Invalid syntax - "+a.name+" disallowed any expressions: "+b):d.f&&(a.error=new SyntaxError("Invalid syntax - "+a.name+
" must have expressions: "+b)):a.error=new SyntaxError("Invalid syntax at "+b);a.c=b}return a}
function Sb(a){var b=a.D,c=b.indexOf(Hb,a.offset),a=j;if(0<=c)if(a={__proto__:r,type:-1,start:c,end:b.indexOf(Ib,c),error:j},0>a.end)a.end=c+1,a.error=new SyntaxError("Missing ending bracket '"+Ib+"' at "+b.substring(c,c+15));else{var b=b.substring(c,a.end+=Jb),c=b.indexOf(Kb,Lb),d;-1!==c?(a.end=a.start+c,a.error=new SyntaxError("Invalid syntax at "+b.substring(0,15))):(c=Mb.exec(b))?c[Nb]?a.type=$.A:!(a.name=c[Ob])||!(d=$[a.name])?a.error=new SyntaxError("Invalid syntax - unknown syntax at "+b):
(a.type=d.type,c[Pb]&&(a.f=c[Pb].replace(Qb,"")),a.F=c[Rb]?l:s)?d.k?a.f&&(a.error=new SyntaxError("Invalid syntax - end of block syntax disallowd any expressions: "+b)):a.error=new SyntaxError("Invalid syntax - "+a.name+" is inline syntax: "+b):a.f?d.f?(d=Fb.analyze(a.f),d.error?a.error=new SyntaxError("Invalid syntax - "+a.name+"\n"+d.error.message):a.b=d.g):a.error=new SyntaxError("Invalid syntax - "+a.name+" disallowed any expressions: "+b):d.f&&(a.error=new SyntaxError("Invalid syntax - "+a.name+
" must have expressions: "+b)):a.error=new SyntaxError("Invalid syntax at "+b);a.c=b}return a}function Tb(a,b,c){var d=b[b.length-1],i=a.D.substring(a.offset,c);d&&!d.type&&!d.name?(d.end=c,d.c+=i):b.push({type:$.H,start:a.offset,end:c,c:i})}function Ub(){return{g:[],stack:[],state:{type:0}}}
var Kb="<?",Lb=Kb.length,Ib="?>",Jb=Ib.length,Hb=Kb+"re",Mb=/<\?re\s+(?:#((?:\s|.)+?)|(\/)?([A-Za-z_]\w{0,})?(?::((?:\r?\n|.)+))?)\s{0,}\?>/m,Nb=1,Rb=2,Ob=3,Pb=4,Qb=RegExp(/^\s+|[\n\r\u2028\u2029]|\s+$/g),Vb={__proto__:r,scan:function(a,b){if("string"===typeof a){for(var c={__proto__:r,D:a,offset:0,J:a.length},d=Ub(),i=d,h=[],e=b?Sb:Gb,f=j,g=j,q=j;f=e(c);){c.offset<f.start&&Tb(c,d.g,f.start);if(f.error)h.push(f),d.g.push(f);else if(f.type!==$.A)if(g=$[f.name],g.n){q=d.stack[d.stack.length-1];if(!q||
!((q.j|q.G.type)&g.n))h.push(f),f.error=new SyntaxError(f.name+" syntax must be nested within ["+g.state+"] block");d.g.push(f)}else f.F?(q=d.stack[d.stack.length-1],!q||q.G.type!==f.type?(h.push(f),f.error=new SyntaxError("end of "+f.name+" syntax must be put after ["+f.name+"] block"),d.g.push(f)):(d.g.push(f),q=d.stack.pop(),q.i&&(i.g.push({type:$.S,g:d.g}),d=i))):(g.k&&(q=d.stack[d.stack.length-1],g.i&&(q&&q.i?(h.push(f),f.error=new SyntaxError("cannot be defined nested macro "+f.c)):d=Ub()),
f.error||d.stack.push({G:f,j:(q?q.j:0)|(g.j?f.type:0),i:g.i})),d.g.push(f));c.offset=f.end}if(q=d.stack[d.stack.length-1])f=q.G,h.push(f),f.error=new SyntaxError("end of ["+f.name+"] syntax not found");c.offset!==c.J&&Tb(c,d.g,c.J);return{m:h,g:i.g}}}};Object.freeze(Vb);Eb.parser=Vb;var Wb=Rez.parser,Xb=Rez.generator,Yb=/[<>"']/g;
Rez.runtime=function(){this.__proto__.compile=function(a,b,c){var d=j;if(!this.hasContext(a))if(c=c?Wb.scan(b,l):Wb.scan(b,s),b=Xb.toCode(c,c.g),c.m.length)d=new SyntaxError("parse error"),d.m=c.m;else for(a in this.__proto__["C$"+a]=new Function(b.e||"",b.src),b.macro)c=b.macro[a],this.__proto__["M$"+a]=new Function(c.e||"",c.src);return d};this.__proto__.hasContext=function(a){return"function"===typeof this["C$"+a]};this.__proto__.removeContext=function(a){return"string"===typeof a?(delete this.__proto__["C$"+
a],l):s};this.__proto__.removeMacro=function(a){return"string"===typeof a?(delete this.__proto__["M$"+a],l):s};this.__proto__.runContext=function(a,b){var c={__proto__:r,ja:"",error:j,U:{__proto__:r},V:b};try{this["C$"+a](c,c.V,c.U)}catch(d){c.error=d}return c};this.__proto__.setBuiltin=function(a,b){var c=s;"string"===typeof a&&(c=l,b&&"function"===typeof b?this.__proto__["B$"+a]=b:delete this.__proto__["B$"+a]);return c};this.__proto__.InitProperty=function(){var a=arguments[0],b=a,c=arguments.length,
d=1,i,h;a:for(;d<c;){h=arguments[d++];a=b;if(!(i=b[h])||d!==c&&"object"!==typeof i){i={};for(b=b[h]=i;d<c;)a=b,h=arguments[d++],i={},b=b[h]=i;a[h]="";break a}b=i}return a};this.__proto__.B$escape=escape;this.__proto__.B$unescape=unescape;this.__proto__.B$encodeURI=encodeURI;this.__proto__.B$decodeURI=decodeURI;this.__proto__.B$encodeURIComponent=encodeURIComponent;this.__proto__.B$decodeURIComponent=decodeURIComponent;this.__proto__.B$isFinite=isFinite;this.__proto__.B$isNaN=isNaN;this.__proto__.B$subcount=
function(a){return"object"===typeof a?Object.keys(a).length:0};this.__proto__.B$htmlStrip=function(a){for(var b="",c=0,d=0,i=0,h;h=Yb.exec(a);)switch(i=h.index,h[0]){case "<":c||(b+=a.substring(d,i),d=i,c|=1);break;case ">":1===c&&(i++,d=i,c&=-2);break;case "'":c&1&&(!(c&4)&&92!==a.charCodeAt(i-1))&&(c=c&2?c&-3:c|2);break;case '"':c&1&&(!(c&2)&&92!==a.charCodeAt(i-1))&&(c=c&4?c&-5:c|4)}c&1||(b+=a.substring(d));return b}};Object.freeze(Rez);try{window.W=Rez}catch(Zb){module.exports=Rez};
